-- ============================================================
-- NearStock — seed data  (GENERATED by scripts/gen-seed-sql.js)
-- Run after db/schema.sql:  mysql -u root -p nearstock < db/seed.sql
-- ============================================================

USE nearstock;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE billing_sync;
TRUNCATE TABLE request_queue;
TRUNCATE TABLE inventory;
TRUNCATE TABLE products;
TRUNCATE TABLE stores;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO users (user_id, name, email, phone, role, latitude, longitude) VALUES
  (1, 'Nirmal R', 'nirmal@nearstock.app', '9876500001', 'customer', 11.0168, 76.9558),
  (2, 'Aravind K', 'aravind@rskirana.in', '9876500002', 'shop', 11.0041, 76.9614),
  (3, 'Meena S', 'meena@greenmart.in', '9876500003', 'shop', 11.0272, 76.9506),
  (4, 'Karthik V', 'karthik@techzone.in', '9876500004', 'shop', 11.051, 76.993),
  (5, 'Divya P', 'divya@medipoint.in', '9876500005', 'shop', 10.9975, 76.947);

INSERT INTO stores (store_id, owner_id, name, category, address, city, phone, latitude, longitude, opens_at, closes_at, rating) VALUES
  (1, 2, 'RS Kirana Store', 'Grocery', '12 Big Bazaar Street, Town Hall', 'Coimbatore', '0422-2390001', 11.0041, 76.9614, '07:00:00', '22:00:00', 4.4),
  (2, 3, 'GreenMart Supermarket', 'Supermarket', '45 Avinashi Road, Peelamedu', 'Coimbatore', '0422-2390002', 11.0272, 76.9506, '08:00:00', '23:00:00', 4.6),
  (3, 4, 'TechZone Electronics', 'Electronics', '8 Cross Cut Road, Gandhipuram', 'Coimbatore', '0422-2390003', 11.0183, 76.9668, '10:00:00', '21:00:00', 4.2),
  (4, 5, 'MediPoint Pharmacy', 'Pharmacy', '3 Trichy Road, Ramanathapuram', 'Coimbatore', '0422-2390004', 10.9975, 76.947, '06:30:00', '23:30:00', 4.8),
  (5, NULL, 'Saravana Stores', 'Grocery', '77 Oppanakara Street, Town Hall', 'Coimbatore', '0422-2390005', 11.0009, 76.9585, '07:30:00', '21:30:00', 4.1),
  (6, NULL, 'Daily Fresh Mart', 'Supermarket', '21 Sungam Bypass, Nanjundapuram', 'Coimbatore', '0422-2390006', 10.9838, 76.9704, '08:00:00', '22:00:00', 4.3),
  (7, NULL, 'Vasanth Electronics', 'Electronics', '90 DB Road, RS Puram', 'Coimbatore', '0422-2390007', 11.006, 76.949, '10:00:00', '20:30:00', 4),
  (8, NULL, 'Anna Medicals', 'Pharmacy', '5 Mettupalayam Road, Thudiyalur', 'Coimbatore', '0422-2390008', 11.081, 76.942, '07:00:00', '23:00:00', 4.5),
  (9, NULL, 'Kovai Book House', 'Stationery', '14 Raja Street, Town Hall', 'Coimbatore', '0422-2390009', 11.0025, 76.964, '09:00:00', '20:00:00', 4.7),
  (10, NULL, 'Peelamedu Provisions', 'Grocery', '62 Hope College Road, Peelamedu', 'Coimbatore', '0422-2390010', 11.0298, 76.9812, '07:00:00', '22:30:00', 3.9);

INSERT INTO products (product_id, name, brand, category, unit, base_price, barcode, image_emoji) VALUES
  (1, 'Aashirvaad Atta 5kg', 'Aashirvaad', 'Grocery', 'pack', 265, '8901030601001', '🌾'),
  (2, 'Amul Butter 500g', 'Amul', 'Dairy', 'pack', 285, '8901030601002', '🧈'),
  (3, 'Aavin Milk 1L', 'Aavin', 'Dairy', 'packet', 54, '8901030601003', '🥛'),
  (4, 'Tata Salt 1kg', 'Tata', 'Grocery', 'pack', 28, '8901030601004', '🧂'),
  (5, 'Sunfeast Marie Light 250g', 'Sunfeast', 'Snacks', 'pack', 45, '8901030601005', '🍪'),
  (6, 'Fortune Sunflower Oil 1L', 'Fortune', 'Grocery', 'bottle', 152, '8901030601006', '🛢️'),
  (7, 'Surf Excel Easy Wash 1kg', 'Surf Excel', 'Household', 'pack', 118, '8901030601007', '🧼'),
  (8, 'Colgate Strong Teeth 200g', 'Colgate', 'Personal Care', 'tube', 112, '8901030601008', '🪥'),
  (9, 'Dettol Handwash 200ml', 'Dettol', 'Personal Care', 'bottle', 99, '8901030601009', '🧴'),
  (10, 'Maggi Noodles 12-pack', 'Nestle', 'Snacks', 'pack', 168, '8901030601010', '🍜'),
  (11, 'Boost Health Drink 500g', 'Boost', 'Beverages', 'jar', 255, '8901030601011', '🥤'),
  (12, 'Bru Instant Coffee 100g', 'Bru', 'Beverages', 'jar', 310, '8901030601012', '☕'),
  (13, 'Paracetamol 500mg (15 tab)', 'Cipla', 'Medicine', 'strip', 22, '8901030601013', '💊'),
  (14, 'Digital Thermometer', 'Dr Morepen', 'Medicine', 'piece', 199, '8901030601014', '🌡️'),
  (15, 'Vicks VapoRub 50ml', 'Vicks', 'Medicine', 'jar', 165, '8901030601015', '🫙'),
  (16, 'boAt Rockerz 255 Earphones', 'boAt', 'Electronics', 'piece', 1299, '8901030601016', '🎧'),
  (17, 'Duracell AA Battery 4-pack', 'Duracell', 'Electronics', 'pack', 185, '8901030601017', '🔋'),
  (18, 'Philips LED Bulb 9W', 'Philips', 'Electronics', 'piece', 149, '8901030601018', '💡'),
  (19, 'Anker 20W USB-C Charger', 'Anker', 'Electronics', 'piece', 1499, '8901030601019', '🔌'),
  (20, 'HDMI Cable 1.5m', 'AmazonBasics', 'Electronics', 'piece', 399, '8901030601020', '🧵'),
  (21, 'Classmate Notebook 200pg', 'Classmate', 'Stationery', 'piece', 60, '8901030601021', '📓'),
  (22, 'Reynolds Pen (Blue, 5)', 'Reynolds', 'Stationery', 'pack', 50, '8901030601022', '🖊️'),
  (23, 'A4 Printer Paper 500 sheets', 'JK Copier', 'Stationery', 'ream', 340, '8901030601023', '📄'),
  (24, 'Basmati Rice 5kg', 'India Gate', 'Grocery', 'pack', 620, '8901030601024', '🍚');

INSERT INTO inventory (store_id, product_id, quantity, price) VALUES
  (1, 1, 24, 262),
  (1, 2, 8, 289),
  (1, 3, 40, 54),
  (1, 4, 60, 27),
  (1, 5, 30, 44),
  (1, 6, 15, 155),
  (1, 7, 12, 120),
  (1, 10, 18, 165),
  (1, 24, 6, 615),
  (1, 22, 25, 50),
  (2, 1, 40, 258),
  (2, 2, 22, 279),
  (2, 3, 85, 52),
  (2, 4, 120, 26),
  (2, 5, 55, 42),
  (2, 6, 34, 149),
  (2, 7, 28, 115),
  (2, 8, 30, 108),
  (2, 9, 26, 95),
  (2, 10, 44, 162),
  (2, 11, 12, 249),
  (2, 12, 9, 305),
  (2, 24, 20, 605),
  (2, 21, 35, 58),
  (3, 16, 14, 1249),
  (3, 17, 40, 179),
  (3, 18, 60, 139),
  (3, 19, 9, 1449),
  (3, 20, 25, 379),
  (4, 13, 150, 21),
  (4, 14, 12, 189),
  (4, 15, 40, 159),
  (4, 8, 20, 110),
  (4, 9, 30, 92),
  (5, 1, 10, 270),
  (5, 3, 25, 55),
  (5, 4, 45, 28),
  (5, 6, 8, 158),
  (5, 10, 0, 170),
  (5, 24, 4, 630),
  (5, 5, 12, 46),
  (6, 1, 18, 259),
  (6, 2, 14, 282),
  (6, 3, 60, 53),
  (6, 7, 20, 116),
  (6, 10, 26, 164),
  (6, 11, 7, 252),
  (6, 12, 5, 315),
  (6, 21, 20, 59),
  (7, 16, 5, 1319),
  (7, 17, 22, 189),
  (7, 18, 33, 145),
  (7, 19, 0, 1520),
  (7, 20, 11, 405),
  (8, 13, 90, 22),
  (8, 15, 18, 168),
  (8, 14, 0, 205),
  (8, 9, 16, 99),
  (9, 21, 120, 55),
  (9, 22, 90, 48),
  (9, 23, 30, 329),
  (10, 1, 9, 268),
  (10, 3, 30, 56),
  (10, 4, 50, 29),
  (10, 5, 20, 47),
  (10, 10, 10, 169),
  (10, 22, 15, 52),
  (10, 21, 12, 62);

INSERT INTO request_queue (store_id, product_id, customer_name, customer_phone, quantity, note, position, status, processed_at) VALUES
  (2, 12, 'Priya M', '9840011122', 1, 'Need before 6pm', 1, 'fulfilled', NOW()),
  (2, 11, 'Rahul S', '9840011133', 2, '', 2, 'waiting', NULL),
  (3, 19, 'Ashwin T', '9840011144', 1, 'Reserve if restocked', 3, 'waiting', NULL),
  (4, 14, 'Lakshmi R', '9840011155', 1, 'For home use', 4, 'waiting', NULL);

SELECT
  (SELECT COUNT(*) FROM stores)        AS stores,
  (SELECT COUNT(*) FROM products)      AS products,
  (SELECT COUNT(*) FROM inventory)     AS inventory_lines,
  (SELECT COUNT(*) FROM request_queue) AS queued_requests;
